### ISSUE TITLE
We can not receive access to zabbix data for Anonymous user in confluence.

### ISSUE THREAD

**Issue by gorya-aleksey** [mesilat/zabbix-plugin#1]
If I make authorization all information received in confluence page . 
 
But  if I don’t make authorization in confluence  and open page as Anonymous I have received massage in page " Zabbix Graph: 401 Client must be authenticated to access this resource. "
 
You  can do access to Zabbix Graph for Anonymous user in confluence ? 
 
Best regards Aleksey.

**Comment by vb-mesilat** [comment]
Hi, Aleksey

Can you install version 1.1.35 pre-release to test this feature? It is located at https://github.com/mesilat/zabbix-plugin/releases/tag/1.1.35

To use anonymous user for Zabbix Graph macro:

- create a Confluence user `zabbix-anonymous`
- navigate to the plugin configuration page (use the plugin `Configure` button) and edit your Zabbix server grantees to include the user `zabbix-anonymous`. You should end up with something like

<img width="1245" alt="Screenshot 2021-02-15 at 12 15 52" src="https://user-images.githubusercontent.com/69499122/107927108-9e2dc580-6f87-11eb-85e3-df8dbfd1bded.png">

- **disable** the user `zabbix-anonymous`

This should let your anonymous users to view Zabbix graphs from the server

**Comment by gorya-aleksey** [comment]
Thx so much it's working very well.
