### ISSUE TITLE
More documentation ?

### ISSUE THREAD

**Issue by vkdk** [mesilat/zabbix-plugin#5]
Hi, 
Is there more documentation for the plugin usage available except for that About page ?

In particular, I'm interested in a complete list of items available for the display. 
From what I can tell, the item names in Zabbix-plugin are not the same as item-keys in Zabbix itself, which makes it hard.

**Comment by vkdk** [comment]
That I've seen, I'm looking for a list (preferably a complete one) of available items I can use in the plugin.

**Comment by mesilat** [comment]
Zabbix items are stored in your Zabbix server so you can look up there.

If you refer to Zabbix plugin macros there are four:

- Zabbix Graph
- Zabbix Item
- Zabbix Triggers
- Zabbix Map

There's also a special type of a macro 'zabbix-host-selector' which is useful to create templates (or Confluence blueprints). This list is complete. All of the plugin's internals are listed here: https://github.com/mesilat/zabbix-plugin/blob/master/src/main/resources/atlassian-plugin.xml

If you need a report or a table with a list of Zabbix items available for a host, would you please detail what columns you want it to have? Please elaborate your requirements.
