### ISSUE TITLE
Visible options in dropdown menu

### ISSUE THREAD

**Issue by nilsbuch** [mesilat/zabbix-plugin#6]
Hi,

When applyin the zabbix macro for confluence (eg. graph) you need to fill out the Zabbux Server, Host and Graph. These are dropdown menus, but unless you know the name of the specific server,host and graph, you can't get any data.

Is there some way to get the drop down menus to visualize the options available on your instans?
Hope you can help.

Best regards
Nils

**Comment by mesilat** [comment]
Hi,
Not yet -- the plugin uses Confluence built-in autocomplete control, that requires some input (at least two characters by default).
It is possible to turn it into pre-filled control, yet it would take some refactoring. Probably be the end of the week

Regards,
Vladislav

**Comment by mesilat** [comment]
Fixed in version 1.1.20
