### ISSUE TITLE
mouseover for serveroptions

### ISSUE THREAD

**Issue by nilsbuch** [mesilat/zabbix-plugin#7]
Hi again,

We experience some issues with choosing the right zabbix server. Is there some way to create a mouseover function that shows the full server name, when hovering over the name?

![image](https://user-images.githubusercontent.com/46489845/53797646-dcff1800-3f36-11e9-95ce-cb46efd3a435.png)

**Comment by mesilat** [comment]
Please update to 1.1.21. That fixes this issue
