### ISSUE TITLE
How to select Triggers from Service?

### ISSUE THREAD

**Issue by alinex** [mesilat/zabbix-plugin#9]
Is it also possible to show triggers from service or from multiple hosts or hostgroups within one macro?

I am currently evaluating your plugin, so far it looks pretty good.

Best regards
A.Schilling

**Comment by mesilat** [comment]
Hi,
This is not possible. So far it is either all hosts or a single host.
You are the first one to request this feature. I can implement it in a week or so

**Comment by mesilat** [comment]
Hi,
It appeared that current Zabbix API ( https://www.zabbix.com/documentation/current/ru/manual/api/reference/trigger/get ) does not provide selecting triggers for a service. However I implemented an option to select triggers for a host group. Please check version 1.1.33 of Zabbix Plugin at Atlassian marketplace

**Comment by alinex** [comment]
That works great, thanks.
